apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-connect
spec:
  provider: vault
  parameters:
    roleName: "mysecret"
    vaultAddress: "http://vault.vault:8200"
    objects:  |
      - secretPath: "secret/data/my-pass"
        objectName:"my-password"
        secretKey: "password"
